name: Build MammaMia Binaries

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.11']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build with PyInstaller
        shell: bash
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then \
            pyinstaller --clean --name MammaMia --onefile \
              --runtime-hook .build/pyi_cwd_to_meipass.py \
              --hidden-import fastapi --hidden-import uvicorn \
              --collect-data dateparser \
              --add-data "config.json;." \
              launcher.py; \
          else \
            pyinstaller --clean --name MammaMia --onefile \
              --runtime-hook .build/pyi_cwd_to_meipass.py \
              --hidden-import fastapi --hidden-import uvicorn \
              --collect-data dateparser \
              --add-data "config.json:." \
              launcher.py; \
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MammaMia-${{ runner.os }}
          path: |
            dist/**

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}